language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Command to install dependencies.
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# Command to run tests.
script: tox
after_success: "coveralls"
