version: 2.1
jobs:
  test_36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run tox -e py36
  test_37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run tox -e py37
