version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run tox -e 3.6
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run tox -e 3.7
