version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
      - image: circleci/python:3.8
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run tox
